<Project Sdk="Microsoft.NET.Sdk">
 
 <PropertyGroup>
   <TargetFramework>net8.0</TargetFramework>
   <RepositoryUrl>https://github.com/LBHackney-IT/asset-shared</RepositoryUrl>
   <Authors>London Borough of Hackney Council</Authors>
   <Company>London Borough of Hackney Council</Company>
   <Copyright>2021</Copyright>
   <Description>Shared library for the Asset domain</Description>
   <NoWarn>S1066;S4457</NoWarn>
   <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
 </PropertyGroup>
 
 <ItemGroup>
   <PackageReference Include="FluentValidation" Version="11.9.0" />
   <PackageReference Include="Hackney.Core.DynamoDb" Version="1.79.0" />
   <PackageReference Include="Hackney.Shared.Tenure" Version="0.14.0" />
   <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
   <PackageReference Include="System.Text.Json" Version="9.0.7" />
 </ItemGroup>
 
</Project>
